version: 2
jobs:
  deployprod:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/firebase-auth-be
    steps:
      - checkout

      - run:
          name: Install Firebase CLI
          command: npm install -g firebase-tools
      - run:
          name: Install Dependencies
          command: cd functions && npm install
      - run:
          name: Test
          command: cd functions && npm run test
      - run:
          name: Build
          command: cd functions && npm build
      - run:
          name: Firebase Deploy
          command: firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deployprod:
          context: eclipx-firebase-vuejs
          filters:
            branches:
              only:
                - master
