version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/firebase-auth-be
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./functions/node_modules
      - run:
          name: Install Dependencies
          command: cd functions && npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./functions/node_modules
      - run:
          name: Test
          command: cd functions && npm run test
      - run:
          name: Build
          command: cd functions && npm build
      - run:
          name: Firebase Deploy
          command: ./functions/node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deployprod:
          context: eclipx-firebase-vuejs
          filters:
            branches:
              only:
                - master
